const FETCH_ALL = 'FETCH_ALL';
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
const FETCH_POST = 'FETCH_POST';
const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const LIKE = 'LIKE';
const DELETE = 'DELETE';
const COMMENT = 'COMMENT';
const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';
const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING';

export {
  FETCH_ALL,
  FETCH_BY_SEARCH,
  FETCH_POST,
  CREATE,
  UPDATE,
  LIKE,
  DELETE,
  COMMENT,
  AUTH,
  LOGOUT,
  START_LOADING,
  END_LOADING,
};
